name: Build Musl Cross Compiler

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        repository: 'richfelker/musl-cross-make'

    - run: |
        cat > config.mak << EOF
        TARGET = x86_64-linux-musl
        DL_CMD = curl -C - -L -o
        BINUTILS_VER = 2.45
        GCC_VER = 15.2.0
        MUSL_VER = 1.2.5
        GMP_VER = 6.3.0
        MPC_VER = 1.3.1
        MPFR_VER = 4.2.2
        ISL_VER = 0.27
        LINUX_VER = 6.12.45
        EOF
        make -j$(nproc)
        make install
        tar -cf output.tar output

    - uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        path: output.tar
