name: Build Musl Cross Compiler

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        repository: 'firasuke/mussel'

    - run: |
        ./mussel -p
        tar -cf toolchain.tar toolchain

    - uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        path: toolchain.tar
